import { typeLanguages } from "./typesTranslations";

export const en:typeLanguages = {
  addMedication: "Add medication",
  addPatient: "Add Patient",
  addPatientForm: "Here would be the form to add a patient",
  capsysDescription:
    "The smart pillbox is a connected device designed to facilitate daily medication management. It syncs with our mobile app to send automatic reminders, personalized alerts, and real-time notifications. Thanks to its functional design and integrated technology, it allows caregivers and users to maintain precise and error-free control over schedules, doses, and administration, improving treatment adherence and peace of mind",
  close: "Close",
  dearUser: "dear user",
  email: "Email",
  error: "Error",
  errorSignUp: "Error signing up, please try again later.",
  friday: "Friday",
  greeting: "Hello, {0}",
  headerTitle: "Header",
  languages: "Languages",
  logOut: "Log Out",
  login: "Login",
  menuHome: "Home",
  menuLogout: "Logout",
  menuProfile: "Profile",
  monday: "Monday",
  more: "more",
  noMedications: "No medications",
  notLoggedIn: "You are not logged in.",
  password: "Password",
  patientDescription: "Patient Description",
  patientName: "Patient Name",
  rememberMe: "Remember me",
  saturday: "Saturday",
  signUp: "Sign Up",
  success: "Success",
  successSignUp: "Sign up successful.",
  successSignUpMessage: "You can now log in with your credentials.",
  sunday: "Sunday",
  thursday: "Thursday",
  tuesday: "Tuesday",
  verifyEmail:
    "We have sent a verification email to your address. Please check your inbox and verify your email to complete the registration process.",
  wednesday: "Wednesday",
  welcomeUser: "Welcome, {0}!",
  welcome: "Welcome to MediTime",
  emailPlaceholder: "Email",
  passwordPlaceholder: "Password",
  loginButton: "Log In",
  forgotPassword: "Forgot your password?",
  createAccount: "Create new account",
  errorEmpty: "Please fill in all fields",
  errorEmail: "Enter a valid email",
  errorPassword: "Password must be at least 8 characters long and contain both letters and numbers",
};
