export const es = {
  addMedication: "Agregar medicamento",
  addPatient: "Agregar Paciente",
  addPatientForm: "Aquí estaría el formulario para agregar un paciente",
  capsysDescription:
    "El pastillero inteligente es un dispositivo conectado diseñado para facilitar la gestión diaria de medicamentos. Se sincroniza con nuestra app móvil para enviar recordatorios automáticos, alertas personalizadas y notificaciones en tiempo real. Gracias a su diseño funcional y tecnología integrada, permite a cuidadores y usuarios llevar un control preciso y sin errores sobre horarios, dosis y administración, mejorando la adherencia al tratamiento y la tranquilidad en el cuidado",
  close: "Cerrar",
  dearUser: "querido usuario",
  email: "Correo electrónico",
  error: "Error",
  errorSignUp: "Error al registrarse, por favor intente más tarde.",
  friday: "Viernes",
  greeting: "Hola, Usuario Administrador",
  headerTitle: "Encabezado",
  languages: "Lenguajes",
  logOut: "Cerrar sesión",
  login: "Iniciar sesión",
  menuHome: "Inicio",
  menuLogout: "Cerrar sesión",
  menuProfile: "Perfil",
  monday: "Lunes",
  more: "más",
  noMedications: "Sin medicamentos",
  notLoggedIn: "No has iniciado sesión.",
  password: "Contraseña",
  patientDescription: "Descripción del paciente",
  patientName: "Nombre del paciente",
  rememberMe: "Recuérdame",
  saturday: "Sábado",
  signUp: "Registrarse",
  success: "Éxito",
  successSignUp: "Registro exitoso.",
  successSignUpMessage: "Ahora puedes iniciar sesión con tus credenciales.",
  sunday: "Domingo",
  thursday: "Jueves",
  tuesday: "Martes",
  verifyEmail:
    "Hemos enviado un correo de verificación a tu dirección. Por favor, revisa tu bandeja de entrada y verifica tu correo para completar el proceso de registro.",
  wednesday: "Miércoles",
  welcome: "Bienvenido",
  welcomeUser: "Bienvenido, {0}!",
  emailPlaceholder: "Correo electrónico",
  passwordPlaceholder: "Contraseña",
  loginButton: "Iniciar Sesión",
  forgotPassword: "¿Olvidaste tu contraseña?",
  createAccount: "Crear nueva cuenta",
  errorEmpty: "Por favor complete todos los campos",
  errorEmail: "Ingrese un email válido",
  errorPassword:
    "La contraseña debe tener al menos 8 caracteres y contener letras y números",
};
